name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.1.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create cache file
      run: echo '${{ matrix.python-version }}' > ./matrix-file.txt

    - name: Install base libraries
      run: pip install setuptools pip  --upgrade --quiet --user

    - name: Install Hatch
      run: pip install --upgrade hatch hatch-pip-compile

    - uses: pre-commit/action@v3.0.1

    - name: Run style checks
      run: |
        hatch run make lint

    - name: Run formatting
      run: |
        hatch run make format

    - name: Run tests
      run: |
        hatch run make test
